---
site_name: "pfhub-schema"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  - Index: index.md
  - About: about.md

remote_branch: gh-pages
remote_name: tkphd
repo_url: https://github.com/tkphd/pfhub-schema
site_url: https://tkphd.github.io/pfhub-schema
